<?php
/**
 * Created by PhpStorm.
 * User: Junjie
 * Date: 10/05/2016
 * Time: 2:23 PM
 */

/**
 * Todo:connect DB for it
 */

//require 'admin/db/connections.php';
require "admin/twilio-php/Services/Twilio.php";
require 'vendor/autoload.php';

use Mailgun\Mailgun;

//start session
session_start();

//initial database
//$dbconnection = new ClientDBConnection();

//get user name
$username = isset($_POST['username']) ? $_POST['username'] :'';
$username = trim($username);
//get user mobile
$mobile =  isset($_POST['mobile']) ? $_POST['mobile'] :'';
$mobile = trim($mobile);

/**
 * do some validation here
 */

//if username is empty, redirect to index page with old input
if($username ==''){

    $_SESSION['oldname'] = $username;
    $_SESSION['oldmobile'] = $mobile;
    $_SESSION['error'] = 'User name cannot be empty';
    header("Location: index.php#quote");
    exit;
}
//if mobile is empty, redirect to index page with old input
elseif($mobile ==""){
    $_SESSION['oldname'] = $username;
    $_SESSION['oldmobile'] = $mobile;
    $_SESSION['error'] = 'Mobile number cannot be empty';
    header("Location: index.php#quote");
    exit;
}

////set up twilio API
$AccountSid = "ACd61bbdbf0ef9a9f000eaf80f7048be92";
$AuthToken = "314d9d2649b50324a53e1e4af37d8767";
$fromNumber = '+61437825267';
$smsBody = "Hi This is Orbella Smash Repair. Thank you for requiring and we will contact you in short time. ".
            "If you want to know further information, please call us on 0431858685 or vist our office ".
            "at 139 New Canterbury RD, Pertersham NSW 2049";

//create twilio instance
$client = new Services_Twilio($AccountSid, $AuthToken);

//send message to customer
try{
    $message = $client->account->messages->create(array(
        "From" => $fromNumber, // From a valid Twilio number
        "To" => $mobile,   // Receiver Number
        "Body" => $smsBody, //SMS Body
    ));
}
//if there is any exception, redirect back
catch(Services_Twilio_RestException $e){

    $_SESSION['oldname'] = $username;
    $_SESSION['oldmobile'] = $mobile;
    $_SESSION['error'] = 'You mobile number is not correct';
    header("Location: index.php#quote");
    exit;
}

//if user mobile is correct, save user into DB
//$result = $dbconnection->saveClient($username,$mobile);
$result = true;


////Instantiate the Mailgun client.
$client = new \Http\Adapter\Guzzle6\Client();
$mailgun = new \Mailgun\Mailgun('key-8cf5f69a23968958aa763fd2d9aecd17', $client);
$domain = "sandboxf22bb67b6e7d4819aed577c421f6a917.mailgun.org";

$send_subject = "You've been contacted by: " . $username;
$send_message =
    "
    Dear Admin,

    You have a new query for smash repair contacted by $username. Please give him or her a callback with the following user details:

        Name: $username
        Mobile: $mobile

    This notification is generated by orbellasmashrepairs automatically. Please do not reply.
        ";

//send email to smash repair admin

try{
$mailgun->sendMessage($domain, array(
    'from'    => 'Smash Repair Notification <admin@orbellasmashrepairs.com.au>',
    'to'      => 'info@orbella.com.au',
    'subject' => $send_subject,
    'text'    => $send_message
));

}
catch(Exception $e){

}

//redirect page based on validation
if ($result){
    $_SESSION['message'] = 'success';
    header("Location: index.php");
    exit;
}
else{

    $_SESSION['oldname'] = $username;
    $_SESSION['oldmobile'] = $mobile;
    $_SESSION['error'] = 'User name or Mobile is not correct';
    header("Location: index.php#quote");
    exit;
}